"""remove resultpath add extension

Revision ID: b2e06de7cf4c
Revises: ce88467caecd
Create Date: 2025-11-20 20:48:56.281317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e06de7cf4c'
down_revision: Union[str, Sequence[str], None] = 'ce88467caecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('path', sa.String(), nullable=False))
    op.add_column('files', sa.Column('extension', sa.String(), nullable=False))
    op.drop_column('files', 'original_path')
    op.drop_column('files', 'result_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('result_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('original_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('files', 'extension')
    op.drop_column('files', 'path')
    # ### end Alembic commands ###
