"""filemodel upd

Revision ID: b6c901c3060b
Revises: 9ca6929ac42d
Create Date: 2025-11-17 22:44:07.359196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c901c3060b'
down_revision: Union[str, Sequence[str], None] = '9ca6929ac42d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'result_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'result_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
