"""folders owner_by column

Revision ID: cd36b672e645
Revises: c2f8463a54cb
Create Date: 2026-01-12 00:24:15.437732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd36b672e645'
down_revision: Union[str, Sequence[str], None] = 'c2f8463a54cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('owner_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folders', 'owner_id')
    # ### end Alembic commands ###
