"""uuid-id

Revision ID: ce88467caecd
Revises: 0176a88822da
Create Date: 2025-11-18 23:08:00.538232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce88467caecd'
down_revision: Union[str, Sequence[str], None] = '0176a88822da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('files', 'uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('uuid', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('files', 'id')
    # ### end Alembic commands ###
